# Generated by Django 4.1.1 on 2022-10-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0002_experimenttype_remove_project_experiment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='project',
        ),
    ]
