# Generated by Django 4.1.1 on 2022-10-05 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0004_alter_differentialsamplecolumn_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
