# Generated by Django 4.1.1 on 2022-10-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0009_remove_differentialanalysisdata_differential_analysis_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='value',
            field=models.FloatField(),
        ),
    ]
