# Generated by Django 4.1.1 on 2022-10-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0011_author_first_author_delete_firstauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_author',
        ),
    ]
