# Generated by Django 4.1.1 on 2022-10-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0013_remove_author_project_project_associated_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='celsus.comparison'),
        ),
    ]
