# Generated by Django 4.1.1 on 2022-10-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0015_remove_file_comparison_comparison_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='project',
        ),
        migrations.AddField(
            model_name='rawdata',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='raw_datas', to='celsus.file'),
        ),
    ]
