# Generated by Django 4.1.1 on 2022-10-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0017_genenamemap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genenamemap',
            name='entry',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
