# Generated by Django 4.1.1 on 2022-11-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0019_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='differentialanalysisdata',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='differential_analysis_datas', to='celsus.comparison'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='raw_sample_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='celsus.rawsamplecolumn'),
        ),
    ]
