# Generated by Django 4.1.1 on 2022-11-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0020_alter_differentialanalysisdata_comparison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='differentialanalysisdata',
            name='gene_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='celsus.genenamemap'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='gene_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='celsus.genenamemap'),
        ),
    ]
