# Generated by Django 4.1.1 on 2022-11-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0028_alter_project_cell_type_alter_project_curtain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='associated_authors',
            field=models.ManyToManyField(related_name='associated_projects', to='celsus.author'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cell_type',
            field=models.ManyToManyField(related_name='projects', to='celsus.celltype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='curtain',
            field=models.ManyToManyField(related_name='projects', to='celsus.curtain'),
        ),
        migrations.AlterField(
            model_name='project',
            name='disease',
            field=models.ManyToManyField(related_name='projects', to='celsus.disease'),
        ),
        migrations.AlterField(
            model_name='project',
            name='experiment_type',
            field=models.ManyToManyField(related_name='projects', to='celsus.experimenttype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='first_authors',
            field=models.ManyToManyField(related_name='first_author_projects', to='celsus.author'),
        ),
        migrations.AlterField(
            model_name='project',
            name='instrument',
            field=models.ManyToManyField(related_name='projects', to='celsus.instrument'),
        ),
        migrations.AlterField(
            model_name='project',
            name='keyword',
            field=models.ManyToManyField(related_name='projects', to='celsus.keyword'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lab_group',
            field=models.ManyToManyField(related_name='projects', to='celsus.labgroup'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organism',
            field=models.ManyToManyField(related_name='projects', to='celsus.organism'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organism_part',
            field=models.ManyToManyField(related_name='projects', to='celsus.organismpart'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantification_method',
            field=models.ManyToManyField(related_name='projects', to='celsus.quantificationmethod'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tissue_type',
            field=models.ManyToManyField(related_name='projects', to='celsus.tissuetype'),
        ),
    ]
