# Generated by Django 4.1.1 on 2022-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0033_rename_gene_names_uniprotrecord_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_parameters',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
