# Generated by Django 4.1.1 on 2022-12-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0035_remove_genenamemap_uniprot_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genenamemap',
            name='primary_uniprot_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='gene_map_primary', to='celsus.uniprotrecord'),
        ),
    ]
