# Generated by Django 4.1.1 on 2022-12-07 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celsus', '0040_alter_curtain_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtain',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curtain',
            name='owners',
            field=models.ManyToManyField(related_name='curtain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curtain',
            name='link_id',
            field=models.TextField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='CurtainAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('token', models.TextField()),
                ('curtain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='access_token', to='celsus.curtain')),
            ],
        ),
    ]
