# Generated by Django 4.1.1 on 2022-12-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0041_curtain_enable_curtain_owners_alter_curtain_link_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='curtain',
        ),
        migrations.AddField(
            model_name='curtain',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='curtain', to='celsus.project'),
        ),
    ]
