# Generated by Django 4.1.1 on 2022-12-19 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celsus', '0043_curtain_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user', models.ManyToManyField(related_name='social_platform', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
