# Generated by Django 4.1.1 on 2022-12-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0044_socialplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtain',
            name='curtain_type',
            field=models.CharField(choices=[('TP', 'Total Proteomics'), ('PTM', 'Post-translational Modification')], default='TP', max_length=3),
        ),
    ]
