# Generated by Django 4.1.1 on 2023-01-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0048_extraproperties_curtain_link_limit_exceed'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproperties',
            name='curtain_post',
            field=models.BooleanField(default=True),
        ),
    ]
