# Generated by Django 4.1.1 on 2023-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0049_extraproperties_curtain_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='differentialanalysisdata',
            name='fold_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='differentialanalysisdata',
            name='significant',
            field=models.FloatField(null=True),
        ),
    ]
