# curl -o /app/celsus/fixtures/diseases.json https://nextcloud1.muttsu.xyz/s/dBnT8tGxjneB4AR/download/diseases.json
# curl -o /app/celsus/fixtures/organisms.json https://nextcloud1.muttsu.xyz/s/saKLFYRj4RqXaDa/download/organisms.json
# docker exec celsusdjango-web-1 python manage.py migrate
# docker exec celsusdjango-web-1 python manage.py loaddata diseases.json
# docker exec celsusdjango-web-1 python manage.py loaddata organisms.json

version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - celsus.env
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    env_file:
      - celsus.env

    depends_on:
      - db
    volumes:
      - ./data/db:/app/media