# curl -o /app/celsus/fixtures/diseases.json https://nextcloud1.muttsu.xyz/s/dBnT8tGxjneB4AR/download/diseases.json
# curl -o /app/celsus/fixtures/organisms.json https://nextcloud1.muttsu.xyz/s/saKLFYRj4RqXaDa/download/organisms.json
# curl -o /app/celsus/fixtures/kinase_library.json https://nextcloud1.muttsu.xyz/s/eL6Y3tQWJcArEzR/download/kinase_library.json
# curl -o /app/celsus/fixtures/data_filter_list.json https://nextcloud1.muttsu.xyz/s/WmgjRrPJFQNEWR5/download/data_filter_list.json
# docker exec celsusdjango-web-1 python manage.py migrate
# docker exec celsusdjango-web-1 python manage.py loaddata diseases.json
# docker exec celsusdjango-web-1 python manage.py loaddata organisms.json
# docker exec celsusdjango-web-1 python manage.py loaddata kinase_library.json
# docker exec celsusdjango-web-1 python manage.py loaddata data_filter_list.json
# docker exec -it celsusdjango-web-1 python manage.py mediabackup -O ./media/testdbbackup2
# docker exec -it celsusdjango-web-1 python manage.py dbbackup -O ./media/testbackup

version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - celsus-net
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: gunicorn celsusdjango.wsgi:application --log-level=debug --bind 0.0.0.0:8000 --timeout 300
    ports:
      - "8000:8000"
    environment:
      - WORKDB_PROFILE=production
      - SECRET_KEY=django-insecure-56n6z$55fer(z9c+=x0e117u6y=t_k-@d_!z-k&5f9x*nt)_hu
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_CORS_WHITELIST=http://curtain.proteo.info,http://curtainptm.proteo.info,http://localhost,http://celsus.proteo.info,http://127.0.0.1,http://localhost:4200
      - DJANGO_ALLOWED_HOSTS=localhost,celsus.muttsu.xyz,127.0.0.1
      - DJANGO_MEDIA_ROOT=/app/media/
      - CURTAIN_ALLOW_NON_STAFF_DELETE=0
      - CURTAIN_ALLOW_NON_USER_POST=1
      - CURTAIN_DEFAULT_USER_CAN_POST=1
      - CURTAIN_DEFAULT_USER_LINK_LIMIT=0
      - Q_CLUSTER_REDIS_HOST=redis
    depends_on:
      - db
      - redis
    volumes:
      - ./data/media:/app/media
    networks:
      - celsus-net
  djangoq:
    container_name: djangoq
    build:
      context: .
      dockerfile: ./docker/Dockerfile-djangoq
    command: python manage.py qcluster
    environment:
      - WORKDB_PROFILE=production
      - SECRET_KEY=django-insecure-56n6z$55fer(z9c+=x0e117u6y=t_k-@d_!z-k&5f9x*nt)_hu
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_CORS_WHITELIST=http://curtain.proteo.info,http://curtainptm.proteo.info,http://localhost,http://celsus.proteo.info,http://127.0.0.1
      - DJANGO_ALLOWED_HOSTS=localhost,celsus.muttsu.xyz,127.0.0.1
      - DJANGO_MEDIA_ROOT=/app/media/
      - CURTAIN_ALLOW_NON_STAFF_DELETE=0
      - CURTAIN_ALLOW_NON_USER_POST=1
      - CURTAIN_DEFAULT_USER_CAN_POST=1
      - CURTAIN_DEFAULT_USER_LINK_LIMIT=0
      - Q_CLUSTER_REDIS_HOST=redis
    depends_on:
      - db
      - redis
    volumes:
      - ./data/media:/app/media
    networks:
      - celsus-net
  netphos:
    build:
      context: D:/PycharmProjects/netphos-web
      dockerfile: D:/PycharmProjects/netphos-web/Dockerfile
    container_name: netphos
    networks:
      - celsus-net
  curtain:
    build:
      context: D:/PycharmProjects/curtain
      dockerfile: D:/PycharmProjects/curtain/Dockerfile
      args:
        API_HOST: https://celsus.muttsu.xyz/
        ORCID_APPID: APP-5RXLC3W1MS2MOW0F
    container_name: curtain
    ports:
      - "8002:80"
  curtainptm:
    build:
      context: D:/PycharmProjects/curtainPTM
      dockerfile: D:/PycharmProjects/curtainPTM/Dockerfile
      args:
        API_HOST: https://celsus.muttsu.xyz/
        ORCID_APPID: APP-5RXLC3W1MS2MOW0F
    container_name: curtainptm
    ports:
      - "8001:80"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - celsus-net


networks:
  celsus-net:
