# curl -o /app/celsus/fixtures/diseases.json https://nextcloud1.muttsu.xyz/s/dBnT8tGxjneB4AR/download/diseases.json
# curl -o /app/celsus/fixtures/organisms.json https://nextcloud1.muttsu.xyz/s/saKLFYRj4RqXaDa/download/organisms.json
# docker exec celsusdjango-web-1 python manage.py migrate
# docker exec celsusdjango-web-1 python manage.py loaddata diseases.json
# docker exec celsusdjango-web-1 python manage.py loaddata organisms.json

version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db
    networks:
      - celsus-net
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: gunicorn celsusdjango.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - WORKDB_PROFILE=dev
      - SECRET_KEY=django-insecure-56n6z$55fer(z9c+=x0e117u6y=t_k-@d_!z-k&5f9x*nt)_hu
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_CORS_WHITELIST=http://curtain.proteo.info,http://curtainptm.proteo.info,http://localhost,http://celsus.proteo.info
      - DJANGO_ALLOWED_HOSTS=http://localhost,http://celsus.muttsu.xyz,http://127.0.0.1
      - DJANGO_MEDIA_ROOT=/app/media/
      - CURTAIN_ALLOW_NON_STAFF_DELETE=0
      - CURTAIN_ALLOW_NON_USER_POST=1
      - CURTAIN_DEFAULT_USER_CAN_POST=1
      - CURTAIN_DEFAULT_USER_LINK_LIMIT=0
    depends_on:
      - db
    volumes:
      - ./data/media:/app/media
    networks:
      - celsus-net
  netphos:
    build:
      context: D:/PycharmProjects/netphos-web
      dockerfile: D:/PycharmProjects/netphos-web/Dockerfile
    container_name: netphos
    networks:
      - celsus-net
networks:
  celsus-net:
