# Generated by Django 4.1.1 on 2022-10-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0003_remove_author_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='differentialsamplecolumn',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='differential_sample_columns', to='celsus.file'),
        ),
        migrations.AlterField(
            model_name='rawsamplecolumn',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_sample_columns', to='celsus.file'),
        ),
    ]
