# Generated by Django 4.1.1 on 2022-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0006_author_project_alter_author_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='differentialanalysisdata',
            name='comparison',
        ),
        migrations.AddField(
            model_name='differentialsamplecolumn',
            name='comparison_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='differentialsamplecolumn',
            name='column_type',
            field=models.CharField(choices=[('P', 'P-value'), ('FC', 'Fold Change')], default='P', max_length=2),
        ),
    ]
