# Generated by Django 4.1.1 on 2022-10-18 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0007_remove_differentialanalysisdata_comparison_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='differentialsamplecolumn',
            name='comparison_name',
        ),
        migrations.RemoveField(
            model_name='differentialsamplecolumn',
            name='file',
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.TextField()),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='celsus.file')),
            ],
        ),
        migrations.AddField(
            model_name='differentialsamplecolumn',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='differential_sample_columns', to='celsus.comparison'),
        ),
    ]
