# Generated by Django 4.1.1 on 2022-10-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0008_remove_differentialsamplecolumn_comparison_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='differentialanalysisdata',
            name='differential_analysis_column',
        ),
        migrations.RemoveField(
            model_name='differentialanalysisdata',
            name='project',
        ),
        migrations.AddField(
            model_name='differentialanalysisdata',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='differential_analysis_datas', to='celsus.comparison'),
        ),
    ]
