# Generated by Django 4.1.1 on 2022-10-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0012_remove_author_first_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='associated_authors',
            field=models.ManyToManyField(related_name='project_associated_authors', to='celsus.author'),
        ),
        migrations.AddField(
            model_name='project',
            name='first_authors',
            field=models.ManyToManyField(related_name='project_first_authors', to='celsus.author'),
        ),
    ]
