# Generated by Django 4.1.1 on 2022-11-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0023_project_ptm_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='differentialsamplecolumn',
            name='column_type',
            field=models.CharField(choices=[('P', 'P-value'), ('FC', 'Fold Change'), ('PS', 'Probability Score'), ('SW', 'Sequence Window'), ('PE', 'Peptide Sequence'), ('PP', 'PTM Position'), ('PI', 'PTM Position in Peptide')], default='P', max_length=2),
        ),
    ]
