# Generated by Django 4.1.1 on 2022-11-10 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0024_alter_differentialsamplecolumn_column_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='lab_group',
            field=models.ManyToManyField(to='celsus.labgroup'),
        ),
    ]
