# Generated by Django 4.1.1 on 2022-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0026_project_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('TP', 'Total Proteomics'), ('PTM', 'PTM')], default='TP', max_length=3),
        ),
    ]
