# Generated by Django 4.1.1 on 2022-11-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0027_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cell_type',
            field=models.ManyToManyField(related_name='cell_types', to='celsus.celltype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='curtain',
            field=models.ManyToManyField(related_name='curtains', to='celsus.curtain'),
        ),
        migrations.AlterField(
            model_name='project',
            name='disease',
            field=models.ManyToManyField(related_name='diseases', to='celsus.disease'),
        ),
        migrations.AlterField(
            model_name='project',
            name='experiment_type',
            field=models.ManyToManyField(related_name='experiment_types', to='celsus.experimenttype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='instrument',
            field=models.ManyToManyField(related_name='instruments', to='celsus.instrument'),
        ),
        migrations.AlterField(
            model_name='project',
            name='keyword',
            field=models.ManyToManyField(related_name='keywords', to='celsus.keyword'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lab_group',
            field=models.ManyToManyField(related_name='lab_groups', to='celsus.labgroup'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organism',
            field=models.ManyToManyField(related_name='organisms', to='celsus.organism'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organism_part',
            field=models.ManyToManyField(related_name='organism_parts', to='celsus.organismpart'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantification_method',
            field=models.ManyToManyField(related_name='quantification_methods', to='celsus.quantificationmethod'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tissue_type',
            field=models.ManyToManyField(related_name='tissue_types', to='celsus.tissuetype'),
        ),
    ]
