# Generated by Django 4.1.1 on 2022-11-21 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celsus', '0029_alter_project_associated_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='associated_authors',
            field=models.ManyToManyField(related_name='associated_project', to='celsus.author'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cell_type',
            field=models.ManyToManyField(related_name='project', to='celsus.celltype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='curtain',
            field=models.ManyToManyField(related_name='project', to='celsus.curtain'),
        ),
        migrations.AlterField(
            model_name='project',
            name='disease',
            field=models.ManyToManyField(related_name='project', to='celsus.disease'),
        ),
        migrations.AlterField(
            model_name='project',
            name='experiment_type',
            field=models.ManyToManyField(related_name='project', to='celsus.experimenttype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='first_authors',
            field=models.ManyToManyField(related_name='first_author_project', to='celsus.author'),
        ),
        migrations.AlterField(
            model_name='project',
            name='instrument',
            field=models.ManyToManyField(related_name='project', to='celsus.instrument'),
        ),
        migrations.AlterField(
            model_name='project',
            name='keyword',
            field=models.ManyToManyField(related_name='project', to='celsus.keyword'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lab_group',
            field=models.ManyToManyField(related_name='project', to='celsus.labgroup'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organism',
            field=models.ManyToManyField(related_name='project', to='celsus.organism'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organism_part',
            field=models.ManyToManyField(related_name='project', to='celsus.organismpart'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owners',
            field=models.ManyToManyField(related_name='project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantification_method',
            field=models.ManyToManyField(related_name='project', to='celsus.quantificationmethod'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tissue_type',
            field=models.ManyToManyField(related_name='project', to='celsus.tissuetype'),
        ),
    ]
