# Generated by Django 4.1.1 on 2022-11-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0030_alter_project_associated_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtain',
            name='file',
            field=models.FileField(default='', upload_to='media/files/curtain_upload/'),
            preserve_default=False,
        ),
    ]
