# Generated by Django 4.1.1 on 2022-11-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0032_uniprotrecord_genenamemap_uniprot_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniprotrecord',
            old_name='gene_names',
            new_name='entry',
        ),
    ]
