# Generated by Django 4.1.1 on 2022-12-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0037_projectsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_default_settings', to='celsus.projectsettings'),
        ),
    ]
