# Generated by Django 4.1.1 on 2022-12-05 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0039_alter_projectsettings_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtain',
            name='link_id',
            field=models.TextField(default=uuid.uuid1, unique=True),
        ),
    ]
