# Generated by Django 4.1.1 on 2022-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0042_remove_project_curtain_curtain_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtain',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
