# Generated by Django 4.1.1 on 2023-01-02 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('celsus', '0045_curtain_curtain_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraProperties',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('curtain_link_limits', models.IntegerField(default=0)),
            ],
        ),
    ]
