# Generated by Django 4.1.1 on 2023-01-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0046_extraproperties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialplatform',
            name='user',
        ),
        migrations.AddField(
            model_name='extraproperties',
            name='social_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_social_platform', to='celsus.socialplatform'),
        ),
    ]
