# Generated by Django 4.1.1 on 2023-01-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0047_remove_socialplatform_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproperties',
            name='curtain_link_limit_exceed',
            field=models.BooleanField(default=False),
        ),
    ]
