# Generated by Django 4.1.1 on 2023-01-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0050_alter_differentialanalysisdata_fold_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
