# Generated by Django 4.1.5 on 2023-01-30 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0052_kinaselibrarymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborators', to='celsus.project'),
        ),
        migrations.AlterField(
            model_name='curtain',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curtain', to='celsus.project'),
        ),
        migrations.AlterField(
            model_name='curtainaccesstoken',
            name='curtain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='celsus.curtain'),
        ),
        migrations.AlterField(
            model_name='differentialanalysisdata',
            name='gene_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='celsus.genenamemap'),
        ),
        migrations.AlterField(
            model_name='extraproperties',
            name='social_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_social_platform', to='celsus.socialplatform'),
        ),
        migrations.AlterField(
            model_name='file',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='celsus.project'),
        ),
        migrations.AlterField(
            model_name='genenamemap',
            name='primary_uniprot_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gene_map_primary', to='celsus.uniprotrecord'),
        ),
        migrations.AlterField(
            model_name='otherpersonnel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_personnels', to='celsus.project'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='celsus.project'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_datas', to='celsus.file'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='gene_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='celsus.genenamemap'),
        ),
        migrations.AlterField(
            model_name='sampleannotation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_annotations', to='celsus.project'),
        ),
    ]
