# Generated by Django 4.1.5 on 2023-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0055_datafilterlist_default_datafilterlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtain',
            name='curtain_type',
            field=models.CharField(choices=[('TP', 'Total Proteomics'), ('PTM', 'Post-translational Modification'), ('F', 'Flex')], default='TP', max_length=3),
        ),
    ]
