# Generated by Django 4.2.2 on 2023-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celsus', '0056_alter_curtain_curtain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilterlist',
            name='category',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
